version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  app:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
        - "5173:5173"
    networks:
      app-network:

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8005:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=300M
    networks:
      app-network:
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_DATABASE=imfeelinglucky
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      app-network:

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      app-network:

  mailcatcher:
    restart: on-failure:10
    container_name: mailcatcher
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      app-network:
